spring:
  application:
    name: spring-security
  datasource:
    url: ${POSTGRES_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # ? Use `update` instead of `create-drop` in dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPR}
  refresh-token-expiration: ${JWT_REFRESH_EXPR}
image:
  max-file-size: 10MB
  allowed-types: image/jpeg,image/png,image/gif
  storage-path: images
  original-image-path: images/original
  optimized-image-path: images/optimized
  processing:
    max-width: 2000 #px, downscale if wider
    max-height: 2000 #px, downscale if taller
    compression-threshold: 2MB # only compress if file > this
    compression-quality: 0.8  # JPEG quality
    supported-types: image/jpeg, image/png, image/gif # types supported by FFmpeg processing
    enable-detailed-logging: true # enable detailed logging for image processing