spring:
  application:
    name: spring-security
  datasource:
    url: ${POSTGRES_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # ? Use `update` instead of `create-drop` in dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPR}
  refresh-token-expiration: ${JWT_REFRESH_EXPR}