ALTER TABLE images ADD COLUMN IF NOT EXISTS original_file_path VARCHA;
ALTER TABLE images ADD COLUMN IF NOT EXISTS original_file_size BIGINT;
ALTER TABLE images ADD COLUMN IF NOT EXISTS optimized BOOLEAN NOT NULL DEFAULT FALSE;